-- Certificate of origin (20261009000200_certificate_of_origin.sql): a member cannot finalize
-- one by calling generate_document directly, only the service role reaches the reviewed
-- path, that path still enforces the actor's membership, and the certificate records the
-- invoice it refers to and the wording it prints.

create extension if not exists pgtap;

begin;
select plan(9);

insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at)
values
  ('00000000-0000-0000-0000-000000000000', 'c7c7c7c7-0000-4000-8000-00000000c7c7', 'authenticated', 'authenticated', 'cleo@owner.test', '', now(), now(), now()),
  ('00000000-0000-0000-0000-000000000000', 'd7d7d7d7-0000-4000-8000-00000000d7d7', 'authenticated', 'authenticated', 'drew@rival.test', '', now(), now(), now());

set local role authenticated;
set local request.jwt.claims = '{"sub":"d7d7d7d7-0000-4000-8000-00000000d7d7","role":"authenticated"}';
select set_config('tests.rival_org', public.create_organization('Rival Origin')::text, true);
set local request.jwt.claims = '{"sub":"c7c7c7c7-0000-4000-8000-00000000c7c7","role":"authenticated"}';
select set_config('tests.org', public.create_organization('Cormorant Exports')::text, true);

with created as (
  insert into public.shipments (org_id, reference, currency, country_of_origin)
  values (current_setting('tests.org')::uuid, 'COO-1', 'EUR', 'DE')
  returning id
)
select set_config('tests.shipment', id::text, true) from created;
insert into public.shipment_items (org_id, shipment_id, position, description, quantity, unit_price, country_of_origin)
values (current_setting('tests.org')::uuid, current_setting('tests.shipment')::uuid, 1, 'Brass valve', 10, 3, 'DE');

-- Other document types are generated by members exactly as before.
select set_config(
  'tests.invoice',
  public.generate_document(current_setting('tests.shipment')::uuid, 'commercial_invoice')::text,
  true
);
select ok(current_setting('tests.invoice') <> '', 'a member still generates a commercial invoice');

select throws_ok(
  $$select public.generate_document(current_setting('tests.shipment')::uuid, 'certificate_of_origin')$$,
  '42501',
  null,
  'a member cannot finalize a certificate of origin by calling generate_document directly'
);
select throws_ok(
  $$select public.generate_certificate_of_origin(
    current_setting('tests.shipment')::uuid, 'c7c7c7c7-0000-4000-8000-00000000c7c7'::uuid
  )$$,
  '42501',
  null,
  'a member cannot call the reviewed path, which is for the service role only'
);
select is(
  (select count(*)::int from public.documents
   where shipment_id = current_setting('tests.shipment')::uuid and kind = 'certificate_of_origin'),
  0,
  'no certificate of origin was stored by the refused calls'
);

-- The application's server, after its own review gate: the service role, for a verified user.
reset role;
set local role service_role;
set local request.jwt.claims = '{"role":"service_role"}';

select throws_ok(
  $$select public.generate_certificate_of_origin(
    current_setting('tests.shipment')::uuid, 'd7d7d7d7-0000-4000-8000-00000000d7d7'::uuid
  )$$,
  '42501',
  null,
  'the reviewed path still refuses a shipment outside the actor''s organizations'
);

select set_config(
  'tests.certificate',
  public.generate_certificate_of_origin(
    current_setting('tests.shipment')::uuid, 'c7c7c7c7-0000-4000-8000-00000000c7c7'::uuid
  )::text,
  true
);
select set_config('request.jwt.claim.sub', '', true);
select set_config('request.jwt.claims', '{"role":"service_role"}', true);

select is(
  (select created_by from public.documents where id = current_setting('tests.certificate')::uuid),
  'c7c7c7c7-0000-4000-8000-00000000c7c7'::uuid,
  'the certificate is recorded as generated by the verified actor'
);
select is(
  (select snapshot -> 'certificate' ->> 'invoice_reference' from public.documents
   where id = current_setting('tests.certificate')::uuid),
  (select number from public.documents where id = current_setting('tests.invoice')::uuid),
  'the certificate records the shipment''s current commercial invoice number'
);
select is(
  (select (snapshot -> 'certificate' ->> 'wording_version')::int from public.documents
   where id = current_setting('tests.certificate')::uuid),
  1,
  'the certificate records the wording version it prints'
);
select is(
  (select snapshot -> 'items' -> 0 ->> 'country_of_origin' from public.documents
   where id = current_setting('tests.certificate')::uuid),
  'DE',
  'the certificate carries the origin country of each line'
);

select * from finish();
rollback;
